# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_geometric_euclidean <- function(X, weights, maxiter, abstol) {
    .Call(`_medians_cpp_geometric_euclidean`, X, weights, maxiter, abstol)
}

cpp_geometric_grassmann <- function(X, weights, maxiter, abstol) {
    .Call(`_medians_cpp_geometric_grassmann`, X, weights, maxiter, abstol)
}

