# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_row_normalize <- function(X) {
    .Call(`_medians_aux_row_normalize`, X)
}

cpp_geometric_sphere_int <- function(X, weights, maxiter, abstol) {
    .Call(`_medians_cpp_geometric_sphere_int`, X, weights, maxiter, abstol)
}

cpp_geometric_sphere_ext <- function(X, weights, maxiter, abstol) {
    .Call(`_medians_cpp_geometric_sphere_ext`, X, weights, maxiter, abstol)
}

cpp_geometric_euclidean <- function(X, weights, maxiter, abstol) {
    .Call(`_medians_cpp_geometric_euclidean`, X, weights, maxiter, abstol)
}

cpp_geometric_grassmann <- function(X, weights, maxiter, abstol) {
    .Call(`_medians_cpp_geometric_grassmann`, X, weights, maxiter, abstol)
}

